export const COMPETENCY_DEFINITIONS: Record<string, string> = {
  // Personality & Behavior
  "Persuading and Influencing": "Effectively convinces, influences, and directs others to gain commitment and alignment.",
  "Relating and Networking": "Builds wide and effective networks of contacts, establishing excellent relationships with stakeholders.",
  "Analyzing and Interpreting": "Comprehends complex information, structures logical arguments, and parses numerical data accurately.",
  "Adapting and Coping": "Responds positively to organizational change, handles high pressure, and adapts behavior to fit conditions.",
  "Working with Stakeholders": "Focuses on client satisfaction, manages expectations, and partners closely across corporate borders.",
  "Leading and Deciding": "Takes initiative, provides clear direction, and makes prompt, well-considered business decisions.",
  "Employee Engagement Factors": "Factors that boost dedication, passion, focus, and drive inside daily team environments.",
  "Intrinsic Drive Alignment": "The level of personal motivation sourced from challenging tasks, responsibility, and growth.",
  "Culture Fit": "Alignment of personal values, collaboration preferences, and mission with organizational standards.",
  "Workplace Preferences": "Favored conditions regarding supervisor communication, autonomy, and collaborative scope.",
  "Leading and Directing": "Guides team members, takes accountability, and governs strategic execution with composure.",
  "Supporting and Cooperating": "Supports colleagues, displays high empathy, and cooperates effectively to build a cohesive unit.",
  "Formulating Concepts & Strategy": "Thinks broadly and strategically, modeling conceptual designs and long-term organizational goals.",
  "Organizing and Executing": "Plans ahead, manages timelines, delivers results with high accuracy, and respects procedures.",
  "Objection Resolution": "Deals with customer disagreements, questions, and roadblocks, steering conversations to win-win solutions.",
  "Negotiation Effectiveness": "Balances concessions and goals during contract discussions to achieve optimal commercial agreements.",
  "Customer Needs Diagnosis": "Asks powerful probing questions to identify real underlying client issues and pain points.",
  "Goal Achievement Drive": "A competitive orientation targeting high quotas, metrics excellence, and consistent personal improvement.",
  "De-escalation Mechanics": "Employs psychological tactics to calm irate customers, resolving tense interactions gracefully.",
  "Empathy & Active Listening": "Paraphrases and processes customer sentiments, ensuring callers feel understood and supported.",
  "Problem Diagnosis & Care": "Systematically identifies customer trouble causes and delivers swift, helpful solutions.",
  "Professional Decorum": "Maintains strict emotional control and adherence to support procedures under high-stress calls.",

  // Cognitive Reasoning
  "Numerical Data Analysis": "Extracts trends, handles proportions, and analyzes financial reporting charts.",
  "Quantitative Problem Solving": "Solves complex mathematical word problems and derives target ratios under timed constraints.",
  "Critical Thinking": "Evaluates facts objectively, avoiding personal assumptions to make logical deductions.",
  "Business Calculations": "Executes basic compound interest, markup, and discount calculations.",
  "Written Comprehension": "Extracts core insights and underlying premises from long-form technical reports.",
  "Information Extraction": "Locates specific, minor data points across long, dry paragraphs of corporate procedures.",
  "Logical Verbal Deduction": "Evaluates whether statements are True, False, or Cannot Say based strictly on text facts.",
  "Pattern Recognition": "Finds spatial, geometric, or alphabetical patterns quickly in complex sequence sets.",
  "Abstract Reasoning": "Evaluates logical transformations of non-verbal symbols to find underlying structural rules.",
  "Conceptual Thinking": "Identifies high-level structural rules in novel, highly ambiguous problems.",
  "Problem Solving": "Synthesizes complex constraints to resolve bottlenecks and optimize workflows.",
  "Logical Troubleshooting": "Systematically eliminates improbable options to find the core issue in a failing system.",
  "Rule Application": "Conforms strictly to standard workflows and operational directives without deviation.",
  "Deductive Logic": "Applies a set of general rules to reach a guaranteed, specific logical conclusion.",
  "Analytical Problem Solving": "Deconstructs heavy systems into simple components to map dependencies.",
  "General Cognitive Agility": "Overall index of learning speed, mental elasticity, and general adaptability.",
  "Rapid Learning": "Measures how fast a candidate picks up completely unfamiliar rules and tools.",
  "Complex Information Processing": "Synthesizes multi-source data feeds simultaneously without losing precision.",
  "Multi-domain Problem Solving": "Adapts solving strategies across numerical, verbal, and symbolic frameworks.",
  "Spatial Visualization": "Mentally holds and manipulates the structure of physical layouts.",
  "Mental Rotation": "Rotates 2D or 3D objects mentally to identify correct matches or alignments.",
  "Geometric Understanding": "Applies standard laws of symmetry, angles, and volumes to resolve visual challenges.",
  "Mechanical Aptitude": "Understanding of basic laws of motion, force, friction, and heat.",
  "Physical Principles": "Grades grasp of gravity, leverage, pulley ratios, and simple fluid dynamics.",
  "Troubleshooting Machinery": "Deduces failure causes in gear assemblies, circuit diagrams, and fluid valves.",
  "Attention to Detail": "Maintains meticulous focus during monotonous comparisons of symbols and strings.",
  "Error Spotting": "Identifies minor differences, spelling mismatches, or calculation mistakes rapidly.",
  "Alphanumeric Comparison Speed": "Speed in evaluating pairs of code strings to check if they are identical.",
  "Arithmetical Accuracy": "Solving standard algebraic formulas with strict adherence to order of operations.",
  "Computational Speed": "Grades high-volume arithmetic throughput under rapid timer constraints.",
  "Mathematical Operations": "Fractions, decimals, percentages, and simple equations calculation skills.",
  "Culture-fair Ability Profiling": "Assesses pure intelligence without language or local school training advantages.",
  "Symbolic Relationship Analysis": "Maps analogies between groups of visual symbols (e.g., A is to B as C is to D).",
  "Visual Logic Deduction": "Deduces state changes in geometric paths based on static rule grids.",

  // Skills & Technical Knowledge
  "Java Syntax & Core APIs": "Grades knowledge of core language libraries, exception handling, and memory types.",
  "Object-Oriented Programming (OOP)": "Grades grasp of polymorphism, encapsulation, abstraction, and inheritance.",
  "Concurrency & Multi-threading": "Grades knowledge of synchronized states, thread locks, executors, and virtual threads.",
  "Troubleshooting Java Applications": "Diagnosing heap leaks, stack exceptions, and thread deadlocks.",
  "Python Data Structures": "Grades performance knowledge of lists, dicts, tuples, sets, and generator expressions.",
  "Algorithmic Problem Solving": "Formulating optimized loops, binary traversals, and dynamic program steps.",
  "Scripting & Automation": "Managing file streams, sub-processes, OS directories, and task schedules.",
  "Pythonic Best Practices": "Adherence to PEP 8, decorators, context managers, and type hints.",
  "Relational Database Querying": "Writing joins, filters, subqueries, CTEs, and index setups.",
  "SQL Optimizations": "Analyzing explain plans, optimizing execution speed, and restructuring nested queries.",
  "Data Manipulation & Aggregation": "Working with window functions, pivots, grouping sets, and rollups.",
  "Database Schema Knowledge": "Primary keys, foreign keys, constraints, normalization, and ACID properties.",
  "C++ Memory Management": "Grades pointer arrays, references, stack/heap spaces, and smart pointers.",
  "Standard Template Library (STL)": "Utilizing dynamic vectors, maps, deques, algorithms, and allocators.",
  "Performance Optimization": "Grades static polymorphism, zero-cost abstractions, inline templates, and cache line alignment.",
  "ES6+ Standards": "Modern JavaScript specs: spread operators, destructuring, modules, and scope bindings.",
  "Asynchronous Operations": "Managing promises, event loops, async/await structures, and call stack queues.",
  "Closures & Scope Dynamics": "Managing lexical scopes, currying patterns, and closure-based variables.",
  "Browser & Web APIs": "Interacting with the DOM tree, fetch triggers, local storage, and worker tasks.",
  ".NET Core Standards": "Working with dependency injection, assembly builds, and .NET Core runtimes.",
  "LINQ & Data Filtering": "Querying collections with standard database-style filtering methods.",
  "Asynchronous Programming": "Using task-based async programming (TAP), threads, and background worker pools.",
  "Type Safety & Generics": "Creating type-safe interfaces, abstract generic classes, and dynamic constraint methods.",
  "Semantic HTML Structures": "Writing clean, modern web layouts adhering to SEO, structure, and readability guidelines.",
  "Responsive CSS (Flexbox/Grid)": "Mastery of screen-responsive media queries, flex containers, and grid placements.",
  "Web Accessibility Standards": "Writing markup accessible to screen-readers (ARIA rules, keyboard focus).",
  "Cross-browser Layout Styling": "Fixing layout rendering issues across Chrome, Safari, Firefox, and Edge engines.",
  "React Hooks & State Flow": "Grades custom hooks, effect hooks, memoization patterns, and parent-child state flows.",
  "Component Composition": "Creating modular, reusable, and container-based frontend web modules.",
  "Performance Tuning": "Grades virtual DOM rendering, state updates minimization, and lazily loaded views.",
  "Ecosystem & Routing Integration": "Integrating router engines, central states, and standard form handlers.",
  "RxJS & Reactive Streams": "Utilizing observables, stream subjects, transformation operators, and stream bundles.",
  "Angular Modules & Routing": "Structuring clean feature modules, lazy-loaded routers, and navigation route guards.",
  "Dependency Injection Flow": "Declaring, configuring, and overriding hierarchical injectors inside Angular elements.",
  "State Management & Forms": "Constructing reactive form validations and central entity states.",
  "Statistical Modeling": "Grades regression, correlation, confidence bounds, and sample sizing.",
  "Machine Learning Algorithms": "Grades random forests, gradient boosting, SVMs, clustering, and neural nets.",
  "Evaluation Metrics & Pipelines": "Grades accuracy, recall, precision, ROC-AUC, cross-validation, and scaling.",
  "Data Preprocessing & EDA": "Data profiling, cleaning null values, encoding variables, and plotting insights.",
  "SOLID Coding Patterns": "Following robust software designs (Single Responsibility, Open-Closed, Dependency Inversion).",
  "Architectural System Design": "Structuring microservices, clean layers, message queues, caching layers, and database replica maps.",
  "Software Testing Paradigms": "Formulating unit, integration, and E2E automation tests.",
  "CI/CD & Version Control": "Managing branch merges, build webhooks, docker deployments, and deployment gates.",
  "OWASP Vulnerability Handling": "Preventing injection attacks, broken auth, XSS, and broken access controls.",
  "Network Protocols & Cryptography": "Working with SSH, TLS, AES encryption, hashing functions, and PKI.",
  "Identity & Access Management (IAM)": "Enforcing RBAC rules, OAuth, JWT verifications, and single sign-on constraints.",
  "Secure System Administration": "Hardening container configurations, environment secrets management, and firewall scopes.",
  "Scrum Events & Artifacts": "Managing backlogs, planning sprints, coordinating standups, and running retros.",
  "Agile Values & Principles": "Fostering self-organization, psychological safety, and iteration-based growth.",
  "Impediment Resolution": "Removing organizational bottlenecks and blocking dependencies.",
  "Team Coaching & Delivery Metrics": "Improving velocity ratios, burn-down trends, and individual agility.",
  "Prioritization Frameworks": "Formulating prioritization matrices (RICE, Kano model, MoSCoW rules).",
  "Roadmap Planning": "Mapping long-term visions to concrete milestones and product releases.",
  "Product Metrics & KPIs": "Measuring active users, retention, churn rates, conversion, and net promoter scores.",
  "Stakeholder Alignment & Strategy": "Communicating features, trade-offs, and timelines across multiple corporate channels.",
  "Financial Statement Mapping": "Constructing double-entry logs and preparing year-end financial sheets.",
  "Ledger Bookkeeping Entries": "Debits, credits, accounting logs, and reconcile loops.",
  "GAAP/IFRS Regulation Standards": "Ensuring calculations strictly match state audit rules.",
  "Cash Flow Analyses": "Tracking operating, investing, and financing capital movements."
};
